{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "64d2a686",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current working directory: c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Programs\\Python\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\ipykernel_15776\\2137714423.py\", line 86, in <lambda>\n",
      "    classify_b = Button(top, text=\"Classify Image\", command=lambda: classify(file_path), padx=10, pady=5)\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\ipykernel_15776\\2137714423.py\", line 63, in classify\n",
      "    pred = numpy.argmax(model.predict([image])[0])\n",
      "  File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\__autograph_generated_fileenu8ply6.py\", line 15, in tf__predict_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2169, in predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2155, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2143, in run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2111, in predict_step\n",
      "        return self(x, training=False)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 30, 30, 3), found shape=(None, 30, 30, 4)\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Programs\\Python\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\ipykernel_15776\\2137714423.py\", line 86, in <lambda>\n",
      "    classify_b = Button(top, text=\"Classify Image\", command=lambda: classify(file_path), padx=10, pady=5)\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\ipykernel_15776\\2137714423.py\", line 63, in classify\n",
      "    pred = numpy.argmax(model.predict([image])[0])\n",
      "  File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\__autograph_generated_fileenu8ply6.py\", line 15, in tf__predict_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2169, in predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2155, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2143, in run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2111, in predict_step\n",
      "        return self(x, training=False)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 30, 30, 3), found shape=(None, 30, 30, 4)\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Programs\\Python\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\ipykernel_15776\\2137714423.py\", line 86, in <lambda>\n",
      "    classify_b = Button(top, text=\"Classify Image\", command=lambda: classify(file_path), padx=10, pady=5)\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\ipykernel_15776\\2137714423.py\", line 63, in classify\n",
      "    pred = numpy.argmax(model.predict([image])[0])\n",
      "  File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"C:\\Users\\kiran\\AppData\\Local\\Temp\\__autograph_generated_fileenu8ply6.py\", line 15, in tf__predict_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2169, in predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2155, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2143, in run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\training.py\", line 2111, in predict_step\n",
      "        return self(x, training=False)\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"c:\\Users\\kiran\\OneDrive\\Desktop\\Traffic Project\\gui_env310\\lib\\site-packages\\keras\\engine\\input_spec.py\", line 298, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 30, 30, 3), found shape=(None, 30, 30, 4)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "from tkinter import *\n",
    "\n",
    "from PIL import ImageTk, Image\n",
    "import os\n",
    "import numpy\n",
    "from gtts import gTTS\n",
    "from keras.models import load_model\n",
    "import pygame\n",
    "import time\n",
    "\n",
    "print(\"Current working directory:\", os.getcwd())\n",
    "\n",
    "global model\n",
    "\n",
    "try:\n",
    "    model = load_model('traffic_classifier.h5')\n",
    "except Exception as e:\n",
    "    print(\"Error loading the model:\", e)\n",
    "\n",
    "classes = {\n",
    "    1:'Speed limit (20km/h)', 2:'Speed limit (30km/h)', 3:'Speed limit (50km/h)',\n",
    "    4:'Speed limit (60km/h)', 5:'Speed limit (70km/h)', 6:'Speed limit (80km/h)',\n",
    "    7:'End of speed limit (80km/h)', 10:'No passing', 11:'No passing veh over 3.5 tons',\n",
    "    12:'Right-of-way at intersection', 13:'Priority road', 14:'Yield', 15:'Stop',\n",
    "    16:'No vehicles', 17:'Veh > 3.5 tons prohibited', 18:'No entry', 19:'General caution',\n",
    "    20:'Dangerous curve left', 21:'Dangerous curve right', 22:'Double curve', 23:'Bumpy road',\n",
    "    24:'Slippery road', 25:'Road narrows on the right', 26:'Road work', 27:'Traffic signals',\n",
    "    28:'Pedestrians', 29:'Children crossing', 30:'Bicycles crossing', 31:'Beware of ice/snow',\n",
    "    32:'Wild animals crossing', 33:'End speed + passing limits', 34:'Turn right ahead',\n",
    "    35:'Turn left ahead', 36:'Ahead only', 37:'Go straight or right', 38:'Go straight or left',\n",
    "    39:'Keep right', 40:'Keep left', 41:'Roundabout mandatory', 42:'End of no passing',\n",
    "    43:'End no passing veh > 3.5 tons'\n",
    "}\n",
    "\n",
    "top = tk.Tk()\n",
    "top.geometry('800x600')\n",
    "top.title('Traffic sign classification')\n",
    "top.configure(background='#CDCDCD')\n",
    "\n",
    "label = Label(top, background='#CDCDCD', font=('arial', 15, 'bold'))\n",
    "sign_image = Label(top)\n",
    "\n",
    "if not os.path.exists(\"audio_outputs\"):\n",
    "    os.mkdir(\"audio_outputs\")\n",
    "audio_counter = 0\n",
    "\n",
    "def play_audio(filename):\n",
    "    pygame.mixer.init()\n",
    "    pygame.mixer.music.load(filename)\n",
    "    pygame.mixer.music.play()\n",
    "    while pygame.mixer.music.get_busy():\n",
    "        continue\n",
    "\n",
    "def classify(file_path):\n",
    "    global model\n",
    "    global audio_counter\n",
    "    image = Image.open(file_path)\n",
    "    image = image.resize((30,30))\n",
    "    image = numpy.expand_dims(image, axis=0)\n",
    "    image = numpy.array(image)\n",
    "    pred = numpy.argmax(model.predict([image])[0])\n",
    "    sign = classes[pred + 1]\n",
    "    print(sign)\n",
    "    audio_filename = f'audio_outputs/output_{audio_counter}.mp3'\n",
    "    audio_counter += 1\n",
    "\n",
    "    if \"Speed limit\" in sign:\n",
    "        speed_limit = sign.split(\"(\")[1].split(\")\")[0]\n",
    "        audio_message = f\"BE ALERT, Speed limit {speed_limit} ahead. Please reduce your speed to {speed_limit}.\"\n",
    "    elif \"Stop\" in sign:\n",
    "        audio_message = \"Be alert, Stop sign ahead. Please come to a complete stop.\"\n",
    "    elif \"Yield\" in sign:\n",
    "        audio_message = \"Be alert, Yield sign ahead. Please yield the right of way.\"\n",
    "    else:\n",
    "        audio_message = f\"Be alert, {sign} ahead. Please drive cautiously.\"\n",
    "\n",
    "    tts = gTTS(text=audio_message, lang='en')\n",
    "    tts.save(audio_filename)\n",
    "\n",
    "    play_audio(audio_filename)\n",
    "    label.configure(foreground='#011638', text=sign)\n",
    "\n",
    "def show_classify_button(file_path):\n",
    "    classify_b = Button(top, text=\"Classify Image\", command=lambda: classify(file_path), padx=10, pady=5)\n",
    "    classify_b.configure(background='#364156', foreground='white', font=('arial', 12, 'bold'))\n",
    "    classify_b.place(relx=0.79, rely=0.46)\n",
    "\n",
    "def upload_image():\n",
    "    try:\n",
    "        file_path = filedialog.askopenfilename()\n",
    "        uploaded = Image.open(file_path)\n",
    "        uploaded.thumbnail(((top.winfo_width()/2.25), (top.winfo_height()/2.25)))\n",
    "        im = ImageTk.PhotoImage(uploaded)\n",
    "\n",
    "        sign_image.configure(image=im)\n",
    "        sign_image.image = im\n",
    "        label.configure(text='')\n",
    "        show_classify_button(file_path)\n",
    "    except:\n",
    "        pass\n",
    "\n",
    "upload = Button(top, text=\"Upload an image\", command=upload_image, padx=10, pady=5)\n",
    "upload.configure(background='#364156', foreground='white', font=('arial', 12, 'bold'))\n",
    "upload.pack(side=BOTTOM, pady=50)\n",
    "sign_image.pack(side=BOTTOM, expand=True)\n",
    "label.pack(side=BOTTOM, expand=True)\n",
    "heading = Label(top, text=\"Know Your Traffic Sign\", pady=20, font=('arial', 22, 'bold'))\n",
    "heading.configure(background='#CDCDCD', foreground='#364156')\n",
    "heading.pack()\n",
    "top.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gui_env310",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
